### ISSUE TITLE
Teste do assistente não executa

### ISSUE THREAD

**Issue by marciosborba** [lappis-unb/rasa-ptbr-boilerplate#111]
Estou tentando rodar o teste do assistente não executa com o comando:

sudo docker-compose up -d rocketchat

Aparece a mensagem: 
sudo: docker-composer: command not found

Tenho o docker e o docker composer instalado corretamente no Ubuntu 18.04 na virtualbox. Estou tentando rodar o assistente numa virtualenv exclusiva para esse projeto.

Tenho acompanhado o trabalho de vocês pelo YouTube. Como sugestão, seria possível fazer um vídeo desde o clone do Github até a execução do teste no Rock Chat e Instagram?

Muito obrigado pelo compartilhamento de conhecimento!

**Comment by RochaCarla** [comment]
Ola @marciosborba !

Que legal que está testando o boilerplate :P

 Ah esse problema acontece com todo mundo ;)

Só tirar o "R" do "composer" no comando "docker-composer". É comum errar esses comandos enormes do docker-compose. Por isso fizemos os make files :)

Por que vc não testa o comando ``make run-rocketchat`` ?

**Comment by marciosborba** [comment]
Bom dia Carla, tudo bem?

Eu consegui carregar o rocketchat, mas o bot não está respondendo, o que posso estar fazendo errado? Muito obrigado

**Comment by pablodiegoss** [comment]
Verifica se o rocket está rodando corretamente com `sudo docker-compose logs rocketchat`, se estiver com algum erro é esse o motivo do bot não estar online.
É comum ver erros do acesso a um icone, do tipo
```
Error while handling the setting of the avatar from a url (https://raw.githubusercontent.com/lappis-unb/rouana/master/images/rouana_avatar.jpeg) for bot: { Error: connect ECONNREFUSED 151.101.92.133:443
rocketchat_1         |     at Object._errnoException (util.js:992:11)
rocketchat_1         |     at _exceptionWithHostPort (util.js:1014:20)
rocketchat_1         |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
rocketchat_1         |
rocketchat_1         |   code: 'ECONNREFUSED',
rocketchat_1         |   errno: 'ECONNREFUSED',
rocketchat_1         |   syscall: 'connect',
rocketchat_1         |   address: '151.101.92.133',
rocketchat_1         |   port: 443 }
```

Se este for o erro, tente reiniciar o rocket e o bot com
```
$ sudo docker-compose down
```
e
```
$ sudo make run-rocketchat
// ou
$ sudo docker-compose up -d rocketchat
$ sudo docker-compose up -d bot
```

**Comment by arthurTemporim** [comment]
Vou fechar a issue por falta de interação.

Por favor reabra caso ainda faça sentido :smile:
