### ISSUE TITLE
Erro ao rodar make train-online

### ISSUE THREAD

**Issue by tomasbarcellos** [lappis-unb/rasa-ptbr-boilerplate#12]
Subi o bot e fui capaz de treiná-lo e usá-lo.

Ao seguir o passo-a-passo sugerido no `readme.md`, contudo, este comando falhou ao rodar:

```
sudo docker-compose run --rm bot make train-online

Starting chatbot_actions_1 ... done
python3 -m rasa_core.train -d domain.yml -s data/stories -o models/dialogue --epochs 15 --online --nlu models/nlu/current/
usage: train.py [-h] {default,compare,interactive} ...
train.py: error: unrecognized arguments: --epochs 15 --online --nlu models/nlu/current/
Makefile:19: recipe for target 'train-online' failed
make: *** [train-online] Error 2
```

Vale notar que não é uma falha que impede o uso do bot/projeto.

**Comment by arthurTemporim** [comment]
Olá @tomasbarcellos , muito obrigado pelo sue aviso, realmente o código no Makefile estava desatualizado, com a atualização da versão do Rasa a forma que estava lá não funcionava mais. 
Encontrei [aqui](https://rasa.com/docs/core/interactive_learning/) a descrição de como usar essa funcionalidade agora. No pull request #21 consegui resolver isso :D
