### ISSUE TITLE
target "run-console" parece ter sido substituído por "run-shell" e demanda atualização nos README's

### ISSUE THREAD

**Issue by lgabs** [lappis-unb/rasa-ptbr-boilerplate#129]
**A sua sugestão de funcionalidade está relacionada a um problema? Descreva**
O Makefile da raíz do projeto tem um target chamado run-shell, mas no README consta que para rodar no terminal usamos o target "run-console". Me parece que é a mesma coisa mas não houve atualização do README.

**Descreva a solução desejada**
Fazer a atualização do README da raíz do projeto

**Tarefas:**
- [ ]  Fazer a atualização do README da raíz do projeto

**Comment by arthurTemporim** [comment]
Muito obrigado pelo report. Esta issue já foi solucionada :ok_hand:
