### ISSUE TITLE
CORS quando utilizo o bot via webchat

### ISSUE THREAD

**Issue by pablodiegoss** [lappis-unb/rasa-ptbr-boilerplate#131]
**Descreva o bug**
Por algum motivo quando uso o run-webchat ou o first-run (que executa o web chat), tenho tomado cors no firefox e connection refused no chrome, mesmo que as urls sejam localhost, não sei como proceder.

Firefox:
![cors](https://user-images.githubusercontent.com/8556291/76456365-a2d01e00-63b5-11ea-8b80-cc37c74704c4.png)

Chrome:
![cors2](https://user-images.githubusercontent.com/8556291/76456396-ae234980-63b5-11ea-811d-65379a0daf73.png)

**Para reproduzir o bug**
Passo-a-passo para reproduzir o comportamento do bug:
1. make first-run
ou 
1. make run-webchat

**Ambiente:**
 - SO: Lubuntu 19.10

**Comment by arthurTemporim** [comment]
Esta issue já está resolvida :smile:
