### ISSUE TITLE
Adicionar testes dockerizados do Chatbot, para NLU e Core

### ISSUE THREAD

**Issue by lgabs** [lappis-unb/rasa-ptbr-boilerplate#136]
Problema: ao usar o boilerplate para iniciar um novo projeto, é necessário criar testes automatizados e, de preferência, independentes, para avaliar o comportamento do bot e assim encontrar melhorias.

**Descreva a solução desejada**
Criar um processo que consiga fazer os testes tanto do modelo NLU como do Core de um chatbot, para o usuário avaliar as performances. Está relacionada ao que foi feito no analytics, mas aqui podemos usar esses testes fora de um ambiente de jupyter notebook, rodando os testes e observando os respectivos outputs diretamente, e de forma independente.

**Tarefas:**
- [x] criar comandos que façam o teste de NLU dockerizado e produzam outputs em uma pasta para o usuário
- [x] idem para o teste do Rasa Core

**Comment by arthurTemporim** [comment]
Como descrito no histório essa issue já foi solucionada pelo @lgabs .

Muito obrigado! :rocket:
