### ISSUE TITLE
Erro ao gerar GZIP (Docker)

### ISSUE THREAD

**Issue by alexlana** [lappis-unb/rasa-ptbr-boilerplate#160]
Olá! 

Usando a versão Docker e segundo as orientações, estou tendo um problema com o arquivo de treinamento salvo em .tar.gz. Recebo essa mensagem:
ERROR    rasa.model  - Failed to extract model at models/20201004-223316.tar.gz. Error: not a gzip file

O trecho do log:

```
Successfully built 478f225e45d1
Successfully tagged hexa_actions:latest
WARNING: Image for service actions was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating hexa_actions_1 ... done
Creating hexa_bot_run   ... done
rasa shell -m models/ -vv --endpoints endpoints.yml --port 5004
2020-10-04 22:34:17 ERROR    rasa.model  - Failed to extract model at models/20201004-223316.tar.gz. Error: not a gzip file
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tarfile.py", line 1646, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/local/lib/python3.7/tarfile.py", line 1623, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/local/lib/python3.7/tarfile.py", line 1486, in __init__
    self.firstmember = self.next()
  File "/usr/local/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/local/lib/python3.7/tarfile.py", line 1094, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/local/lib/python3.7/gzip.py", line 287, in read
    return self._buffer.read(size)
  File "/usr/local/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/lib/python3.7/gzip.py", line 474, in read
    if not self._read_gzip_header():
  File "/usr/local/lib/python3.7/gzip.py", line 422, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\x00\x00')
```

Alguém sabe o que pode estar causando isso? Já pesquisei e tentei fazer alterações no projeto, nas versões/labels da imagem do Python... e nada.

Adorei o trabalho de vcs, agora só preciso conseguir fazer rodar para explorar um pouco.

**Comment by alexlana** [comment]
Olá!

Investiguei mais e descobri que não tem relação com o trabalho de vcs, outras tentativas com projetos existentes ou criando por aqui, em algum momento começa a dar esse erro do "not a gzip". Fiz de tudo relacionado a Docker, desde reiniciar, dar prune em tudo etc, não teve efeito.

O que está funcionando é reiniciar o computador e começar novamente. Parece que o Mac OS tem algum problema relacionado a isso. Tentei em 2 máquinas e o comportamento é o mesmo.

Obrigado!

**Comment by arthurTemporim** [comment]
Olá @alexlana , muito obrigado por abrir esta `issue` pra descrever este problema!

Desculpe pela demora na resposta.

O problema foi resolvido? Pelo que entendio só funciona quando você reinicia a máquina, mas tem algo mais pra gente verfiricar sobre este problema?

**Comment by alexlana** [comment]
Oi, @arthurTemporim ! 

Tudo certo! Obrigado pela atenção e pelo trabalho! :)
