### ISSUE TITLE
Conhecimento do boilerplate

### ISSUE THREAD

**Issue by arthurTemporim** [lappis-unb/rasa-ptbr-boilerplate#187]
# Problema
As conversas do boilerplate estão muito cruas, diferentes e desinteressantes.

# Sugestão de solução
Definir um escopo, talvez uma persona e evoluir os diálogos do projeto é necessário pra ter um exemplo mais vivo de Chatbot RASA.

Um exemplo seria colocar conversas para falar sobre a comunidade RASA brasileira. :brazil: 

## Tarefas
- [ ] Estudar e definir como melhorar os diálogos

> Usem o espaço da issue para discutir sobre as soluções

**Comment by kimuraz** [comment]
Acho que talvez uma boa ideia para o conteudo seria uma "metalinguagem" do bot com os conceitos do proprio bot, por exemplo o que sao actions, stories, nlu, e "guiando" tambem como pode ser usado. O bot seria quase um tutorial dele proprio 😬

**Comment by BrunaNayara** [comment]
Acho uma boa sugestão

**Comment by arthurTemporim** [comment]
Gostei também! vou criar uma primeira versão disso hj 🚀
