### ISSUE TITLE
Problema com o dockerfile para as actions

### ISSUE THREAD

**Issue by thecion** [lappis-unb/rasa-ptbr-boilerplate#193]
**Descreva o bug**
Ao executar um "make run-shell" nesta última versão é exibida uma mensagem de erro pois o arquivo "actions.py" não foi encontrado.

**Ambiente:**
 - SO: Debian
 - Versão 10

** Sugestão **
Ao verificar a estrutura do diretório ./bot/actions percebe-se que as ações foram separadas em arquivos, porém a alteração não foi refletida no actions.Dockerfile

**Comment by RochaCarla** [comment]
Enquanto a gente resolve esse bug, vc tentou subir o contêiner das actions separadamente?
tem o comando make run-actions que sobe o container das actions

**Comment by thecion** [comment]
Ajustei o COPY do dockerfile para fazer a cópia do diretório inteiro. Resolvi abrir a issue para deixar registrado.

**Comment by arthurTemporim** [comment]
Muito obrigado pelo report @thecion corrigi este problema neste [commit](https://github.com/lappis-unb/rasa-ptbr-boilerplate/pull/182/commits/f250415f5b4bd7dcfd9bda2bb9499ee2006409e3) e já está na master :rocket:
