### ISSUE TITLE
engineio and socketio versions in Rasa 2.4.1 are out of sync

### ISSUE THREAD

**Issue by mpomarole** [lappis-unb/rasa-ptbr-boilerplate#204]
**Descreva o bug**
No step `make train` when I run `make first-build`, o seguinte error aparece rodando o `coach`:

```
Cannot import 'json'  from 'engineio'
```

Olhando um [Issue recente no repositorio do Rasa](https://github.com/RasaHQ/rasa/issues/8092), me parece que isso se dá porque as versões do engineio e socketio que o Rasa usava estão imcompativeis.

**Para reproduzir o bug**
Passo-a-passo para reproduzir o comportamento do bug:
1. `make first-build`
2. Veja o erro

**Comportamento esperado**
é esperado que o coach treine o primeiro modelo e rode no Docker container.

**Ambiente:**
 - SO: MacOs com Docker version 20.10.5, build 55c4c88

**Comment by mpomarole** [comment]
O que funcionou para mim, foi fazer o upgrade do Rasa 2.4.1 para 2.5.0.

Vocês já têm uma branch com esse upgrade? Algum motivo para não ir para o 2.5.0. É a primeira vez que estou usando o RASA e o boilerplate então ainda preciso testar para ver se tudo está funcionando antes de sugerir um PR com essa mudança.

**Comment by luizhsalazar** [comment]
Tive o mesmo problema! Subindo a versão do rasa para a 2.5.0 resolveu o/

**Comment by arthurTemporim** [comment]
@mpomarole vc pode, por favor, atualizar a sua `main` e executar o comando `first-run` novamente?

Eu atualizei o projeto nos PRs #206 e #208 e agora o RASA está na versão `2.7.0`.

Além disso eu coloquei a build das depêndencias do projeto no dockerhub [boilerplate-requirements](https://hub.docker.com/repository/docker/arthurtemporim/boilerplate-requirements/general) então se o problema for apenas na instalação não deve acontecer, pois o container já vai ser baixado com tudo instalado.

Fico no aguardo pra saber se deu certo 😄

**Comment by mpomarole** [comment]
@arthurTemporim Obrigada! Eu realmente também atualizei para usar o novo rasa e está funcionando bem. 

> Além disso eu coloquei a build das depêndencias do projeto no dockerhub boilerplate-requirements então se o problema for apenas na instalação não deve acontecer, pois o container já vai ser baixado com tudo instalado.

Muito bom!
