### ISSUE TITLE
Melhorar README

### ISSUE THREAD

**Issue by arthurTemporim** [lappis-unb/rasa-ptbr-boilerplate#27]
Para engajar a comunidade e melhorar a descrição do projeto, a evolução do README deve ser feita. Um bom exemplo é o README da [tais](https://github.com/lappis-unb/tais/blob/master/README.md).

**Comment by pedroeagle** [comment]
os badges do boilerplate são os mesmo do tais? 
license: gpl 3.0 (esse eu vi que é)
maintainability: D
pipeline: passed

**Comment by arthurTemporim** [comment]
@pedroeagle Sim e não. As `badges` usadas na Tais são um bom começo, mas `badges` de testes automatizados, link para documentação e outras relevantes também podem ser adicionadas. Mas o Atualizar o README do boilerplate usando o README da Taís com exemplo seria uma ótima contribuição

**Comment by pedroeagle** [comment]
> @pedroeagle Sim e não. As `badges` usadas na Tais são um bom começo, mas `badges` de testes automatizados, link para documentação e outras relevantes também podem ser adicionadas. Mas o Atualizar o README do boilerplate usando o README da Taís com exemplo seria uma ótima contribuição

estou fazendo algumas melhorias no README me baseando no README da Tais, posso adicionar então as mesmas badges?

**Comment by arthurTemporim** [comment]
> > @pedroeagle Sim e não. As `badges` usadas na Tais são um bom começo, mas `badges` de testes automatizados, link para documentação e outras relevantes também podem ser adicionadas. Mas o Atualizar o README do boilerplate usando o README da Taís com exemplo seria uma ótima contribuição
> 
> estou fazendo algumas melhorias no README me baseando no README da Tais, posso adicionar então as mesmas badges?

Claro, estaremos aguardando o PR \o/
