### ISSUE TITLE
Tutorial - Como calibrar os hyperparâmetros do seu modelo - Rasa Core

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/rasa-ptbr-boilerplate#30]
Criar um tutorial que guie na escolha dos hyperparâmetros dos modelos do chatbot.

## Tarefas

- [x] Como funciona a Policy de um chatbot (as 3 principais camadas: memoization, Keras/Embedding, FallbackPolicy)

- [x]  Passo a passo de como escolher os algoritmos, quais hyperparâmetros, e onde atualizá-los (Keras Policy e Embedding Policy)

- [x] O que significa os hyperparâmetros dos modelos (Keras,Embedding) - falar tb sobre augmentation

- [x] Passo a passo de como calibrar e validar calibração dos hyperparâmetors

## Critérios de Aceitação

- [x] Tutorial em formato Markdown na pasta docs/ do repositório

- [x] Qualquer desenvolvedor é capaz de calibrar os hyperparâmetros dos seus modelos

**Comment by RochaCarla** [comment]
Fazer uma sessão sobre o keras policy e a importância do augmentation factor

1. Para bases de treinamento pequenas (poucas intents/stories), aumentar consideravelmente o augmentation_factor (sugestão usar 50)

2.  Para bases de treinamento grandes (muitas intents/stories), usar um augmentation_factor pequeno (sugestão 20)

Caso não tenha exemplos suficiente para o treinamento do keras_policy, essa policy eh ignorada no pipeline do rasa.core

**Comment by brunapinos** [comment]
Esta documentação se encontra neste [link](https://lappis-unb.github.io/tais/tutorial-como-treinar-o-modelo/)
