### ISSUE TITLE
Adicionar configuração de virtualenv

### ISSUE THREAD

**Issue by arthurTemporim** [lappis-unb/rasa-ptbr-boilerplate#33]
É necessário ter configurações básicas de uso do boilerplate utilizando `virtualenv` além de docker images.

Scripts que ajudem na criação de uso de virtual env e documentações devem ser adicionadas.

**Comment by pedroeagle** [comment]
só pra ficar mais claro: o objetivo da issue é configurar uma venv com os pré-requisitos para utilização/teste do bot?
