### ISSUE TITLE
Dockerização total [Ploc Twist]

### ISSUE THREAD

**Issue by arthurTemporim** [lappis-unb/rasa-ptbr-boilerplate#36]
Com a evolução do `boilerplate` um problema foi identificado, toda a evolução gera um imenso retrabalho de configuração do bot.

Pessando nisso a solução proposta é dockerizar tudo. Simplesmente abstrair toda a pasta `docker` do projeto para um container e publica-lo no `dockerhub`. Dessa forma é necessário apenas uma pasta `data` e um docker-compose para ter um chatbot Rasa.

**Tarefas:**

- [ ] ~Implementar "dockerzão"~
- [ ] ~Publicar no dockerhub "dockerzão"~
- [ ] ~Permitir o treinamento com o Coach em execução, não só durante a build docker~
- [x] Identificar tudo que pode ser abstraído para um container
- [x] Transformar o coach em um FTP para fornecer os modelos do rasa
- [x] Fornecer versão das modelos através de checksum da pasta src_models
- [x] Adaptar o bot para obter as models através do Coach novo
- [x] Bot verificar por atualizações nas modelos baixadas comparando por checksum
- [x] Bot verificar se o coach está disponível
- [x] Configurar bot via variável de ambiente
- [ ] Corrigir a obtenção dos modelos pelo container de notebooks
- [x] Publicar as imagens novas no dockerhub
- [x] Remover a implementação do bot do lappisudo e utilizar as imagens novas

**Critérios de Aceitação**:
- [x] "dockerzão" implementado
- [x] A garantia que a solução evita retrabalhos
- [x] É possível implementar um bot criando apenas o seu próprio coach

**Comment by pablodiegoss** [comment]
Essa issue foi priorizada para definitivamente desacoplar o treinamento das modelos e o bot.
A estratégia planejada para execução desta tarefa é a transformação do bot em um serviço isolado, configurado através de variáveis de ambiente. E o que chamamos de Coach hoje ser transformado em um serviço similar a um banco de dados, porém, como nossos "dados" são os arquivos de model, será então um servidor ftp acessível para o bot via hostname ou URL.
A proposta então é transformar o nosso uso do Bot a um serviço mais próximo então de um modelo servidor web + database, onde teremos então o Bot stateless e os modelos que utiliza para conversar armazenados em outro serviço.

Estas modificações devem permitir remover as implementações do bot de todos os outros repositórios e apenas utilizarem a imagem provida por este projeto. Cada bot então terá apenas a implementação das suas intents, stories e utters.

**Comment by pablodiegoss** [comment]
Solução sendo trabalhada na branch: [ploc-v3](https://github.com/lappis-unb/rasa-ptbr-boilerplate/tree/ploc-v3)

**Comment by LeoSilvaGomes** [comment]
Foi criado o arquivo model_downloader.py, que verifica a existência do arquivo models.tar.gz e baixa se necessário.

commit: [Generate models downloader ](https://github.com/lappis-unb/rasa-ptbr-boilerplate/commit/41d7302563ea2c4bfee1eca18f33b55cd39ce425)

**Comment by LeoSilvaGomes** [comment]
O bot está preparado para receber remotamente as models de um coach e não mais diretamente via dockerfile.

Agora é possível remover o arquivos de bot do lappisudo e começar os testes dessa nova arquitetura.

**Comment by pablodiegoss** [comment]
Terminamos as mudanças do coach para que seja extensível e configurável para usuários que desejarem. Publiquei as imagens no meu dockerhub pessoal para podermos realizar testes nos outros repositórios, essas imagens são: pablodiegoss/bot:boilerplate e pablodiegoss/coach:boilerplate
Então prosseguimos para o repositório do [lappisudo](https://github.com/lappis-unb/lappisudo). Lá criamos uma branch ploc_validation onde montamos a estrutura de um bot utilizando essas novas imagens para prova de conceito, lá removemos a implementação do bot e no coach apenas fornecemos os dados (intents, stories e utters) e as configurações de nlu e policy.

@arthurTemporim pode verificar o progresso lá no lappisudo? Para mergear essas modificações aqui no boilerplate é necessário modificar o pipeline um pouco para publicar as novas imagens e atualizar a documentação. Mas gostaria de um feedback antes de sair concluindo tudo já que essas mudanças acabam mudando a forma que o boilerplate funciona e como as pessoas podem criar seus bots.

**Comment by arthurTemporim** [comment]
@pablodiegoss @LeoSilvaGomes Vocês podem criar um `Draft PR` dessa branch? Fica bem mais fácil pra ver as mudanças com a `devel`.

**Comment by arthurTemporim** [comment]
Olhei o [Lappisudo](https://github.com/lappis-unb/lappisudo/tree/ploc_validation) e tenho algumas considerações:


* Por que no `Lappisudo` a pasta `bot` foi apagada e no `boilerplate` não?
O `boilerplete` vai conter todos os arquivos de configurações e um bot que herdar do boilerplate não vai ter os aquivos dessa pasta, certo?

* Como que faz pra atualizar um bot filho? Por exemplo, quero conectar meu bot no `slack` mas preciso do arquivo `endpoint.yml` pra isso como faz em um bot que herda do `boilerplate`?

* Como faz pra executar o próprio `Lappisudo` na `RocketChat` ou `Telegram` com essa configuração?
Só precisa atualizar o `command` do `docker-compose`, certo?

* Pra criar um bot do 0 com essa configiuração o mais importante é a pasta `data/` e o `docker-compose`, com isso da pra ter um bot Rasa?

**Comment by pablodiegoss** [comment]
MASSA! 
Vou comentar ponto a ponto o que tenho.

>     * Por que no `Lappisudo` a pasta `bot` foi apagada e no `boilerplate` não?
É uma prova de conceito, pois com a nova configuração daria pra fazer um bot simples sem necessariamente fazer um fork do boilerplate, apenas utilizando o bot de lá como serviço e imagem docker no compose. E caso a pessoa queira evoluir o especificamente o bot, aí sim, forkar o boilerplate e teria a pasta bot pra ser evoluido.
No caso do lappisudo, nossa ideia é ter só conteudo do lappis mesmo, melhor não ter as coisas específicas do bot, já deixei como essa versão 'clean'.

>       O `boilerplete` vai conter todos os arquivos de configurações e um bot que herdar do boilerplate não vai ter os aquivos dessa pasta, certo?
Isso, separei no coach inclusive uma pasta base_config que é padrão, um coach filho só precisa ou pode sobrescrever a pasta config. A base_config é oculta dele, com padrões tipo makefiles, train.py e arquivos normalmente não modificados por ninguém que vai utilizar um coach.

>     * Como que faz pra atualizar um bot filho? Por exemplo, quero conectar meu bot no `slack` mas preciso do arquivo `endpoint.yml` pra isso como faz em um bot que herda do `boilerplate`?

Esse é um caso que eu não tenho certeza ainda e podia ver com você, mas o que eu pensei é conseguirmos configurar estes canais apenas por variáveis de ambiente. Se alguém quiser contribuir adicionando um novo canal pro bot, faria direto no boilerplate mesmo, centralizando as evoluções do bot todas no boilerplate.
Hoje já temos os make run-**** que rodam determinados conectores e o bot.env que configura os canais do rocket, pensei em manter essa ideia pra todos os canais.

>     * Como faz pra executar o próprio `Lappisudo` na `RocketChat` ou `Telegram` com essa configuração?
>       Só precisa atualizar o `command` do `docker-compose`, certo?
Exatamente
 
>     * Pra criar um bot do 0 com essa configiuração o mais importante é a pasta `data/` e o `docker-compose`, com isso da pra ter um bot Rasa?
Exatamente (2). Um serviço coach com a pasta data e config (já que as policies lá e nlu_config são bem mutáveis também pelo que entendo), mas além disso só o compose com o bot, coach e as variáveis de ambiente.

**Comment by arthurTemporim** [comment]
Link do PR [aqui](https://github.com/lappis-unb/rasa-ptbr-boilerplate/pull/68)

**Comment by arthurTemporim** [comment]
Bom depois dessas explicações está tudo mais claro pra mim. E parabéns todas essas evoluções estnão **MUITO** eficientes! Acho super válido e concordo com elas.

* Teremos que fazer um esforço pra colocar CI, testes automatizados, lint checkers e padronizar o máximo `boilerplate` depois que esse PR for mergado.
* Também fazer tutoriais e vídeos sobre.

Tem outra grande evolução a caminho que é a #63 to atualizando a versão do Rasa nela, temos que sincronizar os PRs.

Existe algo mais a ser implementado? @pablodiegoss @LeoSilvaGomes

**Comment by LeoSilvaGomes** [comment]
Para ser implementado ainda não, só as correções que você citou no PR, vamos trabalhar nelas e colocaremos para revisão! @arthurTemporim
