### ISSUE TITLE
Conexão com o telegram por meio de arquivo python

### ISSUE THREAD

**Issue by joaovitor3** [lappis-unb/rasa-ptbr-boilerplate#38]
Atualmente o `boilerplate` realiza a conexão com o telegram por meio desse comando no Makefile:
```
run-telegram:
	python -m rasa_core.run -d /models/dialogue -u /models/nlu/current --port 5001 --credentials credentials.yml --endpoints endpoints.yml
```
Isso poderia ser realizado por meio do telegram input em um arquivo python (assim como a conexão do rocketchat é feita por meio do arquivo em bot/run-rocketchat.py) conforme mostrado nesse [link da documentação do rasa](https://legacy-docs.rasa.com/docs/core/connectors/#id11) e na imagem a seguir:

![image](https://user-images.githubusercontent.com/18130942/60456844-c29d2880-9c10-11e9-9a6a-fa70cc4e00e0.png)

**Comment by pablodiegoss** [comment]
@rodrigocam está trabalhando nesta issue. O rasa modificou a forma como se inicia um servidor e os conectores, então o trabalho já está levando em conta a versão nova 1.2.2

**Comment by arthurTemporim** [comment]
Esta Issue está desatualizada na versão do Rasa e na forma que a integração com o Telegram funciona, o correto é utilizar o `credentials` para isso.
