### ISSUE TITLE
Problema na utilização do TensorFlow

### ISSUE THREAD

**Issue by arthurTemporim** [lappis-unb/rasa-ptbr-boilerplate#39]
Após executar o comando `sudo make first-run` o seguinte erro acontece:
```
bot_1_d64506d9a1d9 | make[1]: Leaving directory '/bot'
bot_1_d64506d9a1d9 | python3 run-rocketchat.py
bot_1_d64506d9a1d9 | 2019-07-02 15:16:31.670672: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
bot_1_d64506d9a1d9 | make: * [run-rocketchat] Aborted (core dumped)
bot_1_d64506d9a1d9 | Makefile:2: recipe for target 'run-rocketchat' failed
```
Um comentário com problema semelhante aponta que o problema pode estar no TensorFlow [aqui](https://superuser.com/questions/1398548/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u), e nesse [link](https://www.tensorflow.org/install/pip) diz que as instruções `AVX` podem não funcionar em CPUs antigas.

**Comment by brunapinos** [comment]
Como o Rasa tem como dependência o `tensorflow==1.13.1`, o computador deve seguir os requisitos de hardware para rodá-lo, como mostra no segundo link comentado pelo @arthurTemporim.

**Comment by arthurTemporim** [comment]
Entendi, creio então que isso não é um **bug** e sim um "pre-requisito". Vou fechar a issue então. Obrigado!
