### ISSUE TITLE
Criar módulo de integração com ElasticSearch

### ISSUE THREAD

**Issue by arthurTemporim** [lappis-unb/rasa-ptbr-boilerplate#41]
A integração do boilerplate com Elastic search é feita [aqui](https://github.com/lappis-unb/rasa-ptbr-boilerplate/blob/88c9e8fdfd6b4d8eb68641f3e0d4b9c5bcb494bd/bot/run-rocketchat.py#L31), no script `run-rocketchat.py`. Porém caso queira coletar os dados de outro mensageiro é necessário refazer essa configuração em outro script.

O objetivo é fazer com que a integração com o ElasticSearch seja feita de forma direta, e não apenas na integração com a Rocket.Chat.

**Comment by guilacerda** [comment]
Além de tirar a dependência do rocketchat é necessário fazer a documentação.

**Comment by joaovitor3** [comment]
Issue finalizada por esse [Pull request](https://github.com/lappis-unb/rasa-ptbr-boilerplate/pull/60)
