### ISSUE TITLE
[Kibana] Diferenciação de usuário

### ISSUE THREAD

**Issue by guilacerda** [lappis-unb/rasa-ptbr-boilerplate#73]
**Descrição**

Foi disponibilizado a feature de segurança que faz a diferenciação de usuário no plano Basic, após a atualização do Kibana para a versão 7.3.0. Com isso, não existe mais a necessidade de mantermos os serviços do dados.lappis.rocks e do analytics.lappis.rocks. São serviços que criamos para fazer a diferenciação de usuários. 

É preciso estudar como que faz para configurar os usuários na nova versão.

**Tarefas**
- [ ] ~Habilitar o _security_ no elastic~
- [ ] ~Criar usuário administrador com total permissão~
- [ ] ~Criar usuário apenas para visualização dos dashboards, sem direito a editar~

**Critérios de aceitação**

- [ ] ~É possível acessar como administrador e editar os dashboards/visualizações~
- [ ] ~É possível acessar o kibana como usuário comum somente para visualizar, sem permissão para editar os dashboards/visualizações~

**Comment by joaaogui** [comment]
Caso não seja feito o update do kibana em produção, boa parte da issue se torna de documentação. Com isso em mente, criei um tutorial passo a passo de como se ativar a função de segurança e configurá-la, no README do projeto (branch elastic_security link: https://github.com/lappis-unb/rasa-ptbr-boilerplate/tree/elastic_security#configurando-os-usu%C3%A1rios). PR #87
