### ISSUE TITLE
Estudar e documentar migração para o kubernetes

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/rasa-ptbr-boilerplate#74]
**Descrição**

A infra do lappis está no kubernetes, deve-se entender como funciona a mudança do lappisudo para o kubernets, e documenta-la

PS: Deve-se usar a branch ploc-validation

Aparentement, o davi está fazendo a issue de migrar o lappisudo, checar com ele.

**Tarefas**
- [ ] Migrar lappisudo para pod do kubernetes

**Critérios de aceitação**

- [ ] Lappisudo deve estar migrado para o kubernetes
- [ ] Deve existir uma docmentação passo-a-passo genérica afim de se auxiliar a migração do boilerplate

**Comment by arthurTemporim** [comment]
Esta issue não faz mais sentido no projeto
