### ISSUE TITLE
Adicionar integração contínua

### ISSUE THREAD

**Issue by arthurTemporim** [lappis-unb/rasa-ptbr-boilerplate#8]
Descrição
Implementar integração contínua usando preferencialmente `gitlab-ci` deve ser implementado para verificar se todo o `boilerplate` está funcionando corretamente.

Tarefas:
- [ ] Realizar mirror do repositório para o gitlab
- [ ] Configurar arquivo .gitlab-ci.yml com os stages que foram utilizados na [tais](https://github.com/lappis-unb/tais)

Critérios de aceitação:
- [ ] Pipeline ser executado corretamente no gitlab

**Comment by victorcmoura** [comment]
Reimplementing pipeline after plocv3

**Comment by MatheusMiranda** [comment]
Atualizar com as otimizações do pipeline #574
