### ISSUE TITLE
Recepcionar o usuário automáticamente

### ISSUE THREAD

**Issue by pablodiegoss** [lappis-unb/rasa-ptbr-boilerplate#80]
@MatheusRich comentou comigo que acessou o Lappisudo e sentiu falta de uma interação inicial do bot na página. Acessando a página do lappis, o bot aparece lá no cantinho e a caixa de texto fica vazia, o usuário tem que "adivinhar" que a caixa de texto é um chatbot e que ele deve conversar por ali.

Procurei nas issues e não consegui encontrar algo relacionado a recepcionar usuário, mas o que ele procurava era uma recepção automática do bot "Oi, sou um chatbot, se quiser falar comigo é só digitar aqui". Similar a chatbots de sites de compras, isso é possível implementar? é problema? como fazer?

**Comment by guilacerda** [comment]
Acredito que a solução seja por alguma configuração do Livechat da Rocket.Chat, e não por parte do Rasa.

**Comment by arthurTemporim** [comment]
Esta issue não faz mais sentindo na configuração atual, este conteúdo já foi adicionado:
https://github.com/lappis-unb/rasa-ptbr-boilerplate/blob/0dead99d2c758ccfbacf97acdaf634213ee76491/bot/domain.yml#L85
