### ISSUE TITLE
Atualização do CI/CD

### ISSUE THREAD

**Issue by arthurTemporim** [lappis-unb/rasa-ptbr-boilerplate#85]
**Descreva o bug**
O CI atual não está funcionando, ele deve ser corrigido ou outra solução configurada.

**Comment by arthurTemporim** [comment]
@victorcmoura você pode atualizar esta issue, por favor?

**Comment by staticdev** [comment]
@arthurTemporim parece que isso já tá resolvido né? =p

**Comment by arthurTemporim** [comment]
@staticdev está sim, coloquei na última release e esqueci de ataulizar esta issue. 

A configuração foi feita no [github workflows](https://github.com/lappis-unb/rasa-ptbr-boilerplate/blob/master/.github/workflows/python.yml) e é possível verificar os testes nesta [build](https://github.com/lappis-unb/rasa-ptbr-boilerplate/runs/828957837).

Estou pensando em como melhorar o CI pra validar mais partes do projeto como a parte de métricas e os outros modulos, mas por enquanto está ok :smile: 

Muito obrigado pelo aviso!
