### ISSUE TITLE
implementar testes de conversação

### ISSUE THREAD

**Issue by arthurTemporim** [lappis-unb/rasa-ptbr-boilerplate#9]
O Rasa desenvolveu uma solução para testes de conversação, implemeter testes capazes de verificar o comportamento do chatbot relacionado à conversação devem ser implementados.
[Rasa testes de conversação](https://rasa.com/docs/core/evaluation/#end-to-end-evaluation)

**Comment by joaovitor3** [comment]
Issue finalizada por meio desse [Pull Request](https://github.com/lappis-unb/rasa-ptbr-boilerplate/pull/61)
