### ISSUE TITLE
Documentar Ecossistemas de SL

### ISSUE THREAD

**Issue by MatheusMiranda** [lappis-unb/rasa-ptbr-boilerplate#90]
**Descrição**
Coletar métricas dos repositórios do Ecossistema de Software Livre (TED MinC)

**Tarefas**
- [ ] Selecionar métricas a serem coletadas
- [ ] Criar notebook geral
- [ ] Criar notebook Tais
- [ ] Criar notebook SalicML
- [ ] Criar notebook Promova Cultura
- [ ] Criar notebook BotFlow
- [ ] Mapear se há mais repositórios a possuirem notebooks
- [ ] Verificar se contribuições a outros softwares livres entram nas métricas (contribuições no Rasa, RocketChat...)

**Critérios de Aceitação**
- [ ] Métricas validadas com algum sênior
- [ ] Notebooks criados
- [ ] Notebooks validados por algum sênior

**Comment by arthurTemporim** [comment]
Issue movida para Tais [#587](https://github.com/lappis-unb/tais/issues/587).
