### ISSUE TITLE
Consertar README e pontos do Boilerplate

### ISSUE THREAD

**Issue by MatheusMiranda** [lappis-unb/rasa-ptbr-boilerplate#91]
**Descrição**

É necessário subir toda a stack do boilerplate para validar se toda a documentação do README está correto e todos os comandos estão funcionando corretamente. Cada erro encontrado é necessário documentar e consertar.

**Tarefas**

- [x] Executar todos os comandos do README para ver se estão funcionando corretamente
- [x] Relatar nesta issue os erros encontrados
- [x] Consertar os erros encontrados e relatados

**Critérios de aceitação**

- [ ] É possível subir toda a stack do boilerplate a partir do README sem nenhum problema

**Comment by guilacerda** [comment]
> Agora o problema encontrado foi no Kibana.
> 
> Ao importar os Dashboards o índice não vem junto das visualizações. Sendo salvo apenas as próprias visualizações e os dashboards. Como esses elementos utilizam o id do índice, todas as visualizações estão quebradas.
> 
> Analisar quais das opções abaixo é mais viável.
> 
> * [x]  Fazer com que o script importe também o índice.
> 
> **ou**
> 
> * [ ]  ~Fazer com que as visualizações utilize o índice já existente no Kibana/Elastic, não necessitando a importação.~

O problema concreto se dava pelo fato de que todas as visualizações/dashboards quando criados ficam referenciados ao index escolhido em sua criação. Com isso, as visualizações tinham sido criadas no kibana da Tais, fazendo com que essa referencia fosse para o índice de lá. Então foi necessário fazer com que ao importar os dashboards ele também importasse/criasse um índice com o mesmo **id** do index da Tais.

Para resolver esse problema foi necessário investigar como que funcionava a API do Kibana. Com isso, foi identificado que era possível através de uma requisição post criar um index-pattern no Kibana com um custom id. Utilizei dessa ideia para setar como padrão esse novo indice criado e que ele utilizasse o id do index da Tais. Assim o problema de importação encontra-se resolvido. 

Não é necessário executar mais nenhum comando adicional, basta rodar o mesmo comando para importação dos dashboards.
